### ISSUE TITLE
[up to date] I have a PR to submit

### ISSUE THREAD

**Issue by Slals** [fingera/react-native-secp256k1#3]
Hey,

I updated the lib so that it is compatible with last versions of RN. Would you add it to this repo and publish it in package manage?

Since it changes the code structure I created a new branch called `v1.1` https://github.com/Slals/react-native-secp256k1/tree/v1.1

It doesn't change de core code, it fixes imports and build configs.

I exported the source for iOS in a pod you can find here https://github.com/Slals/bitcoincore-pod-specs

Let me know! If you don't respond I will submit a new package, but it's best to keep it under your name since it's your code.

**Comment by Slals** [comment]
@fingera

**Comment by fingera** [comment]
OK
